### ISSUE TITLE
PipelineExecutor does not allow to close internal resources

### ISSUE THREAD

**Issue by grnadav** [logzio/sawmill#172]
Hi

We recently started using Sawmill, and noticed a thread leak issue.
We tracked it down to creation of multiple instances of `PipelineExecutor` s -
It internally allocates a watchdog, which allocates an Executor, but the PipelineExecutor does not expose a `close` method to close it when done.

I created a (very small) pull request w/ a fix:
https://github.com/logzio/sawmill/pull/171

Thanks

**Comment by oririechman** [comment]
Merged!
Thanks!
