### ISSUE TITLE
Changes to GeoLite2 license and distribution will cause problems for this project

### ISSUE THREAD

**Issue by 2shortplanks** [logzio/sawmill#193]
The [URL](https://github.com/logzio/sawmill/blob/6d69a529cf8890ca68da7b82749f10280e6ed3dc/sawmill-core/pom.xml#L17) in the maxMindGeoIpCityUrl property will stop functioning on December 30th.

Due to upcoming data privacy regulations, MaxMind are making significant changes to how users access free MaxMind GeoLite2 databases starting December 30, 2019. The databases will continue to be available without charge and for redistribution. However, you will be required to create an account and use a license key to download the databases, and agree to a new EULA that addresses applicable data privacy regulations.

Learn more on the MaxMind blog: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/.

Mark Fowler
MaxMind

**Comment by barakm** [comment]
This issue was resolved by making the database file download URL injectable, as described at: https://github.com/logzio/sawmill/wiki/GeoIp-Processor
