### ISSUE TITLE
The spelling mistake “Substitue Processor” in Wiki

### ISSUE THREAD

**Issue by jamesyoung28** [logzio/sawmill#257]
hello，
 when I see the wiki，I find a spelling mistake，
the “Substitue Processor”，the spelling of word “substitue” should be “substitute”，you lost the “t”
![sub](https://user-images.githubusercontent.com/44920599/125045839-019fc780-e0d0-11eb-8006-3951502e8fc6.jpg)

**Comment by jkowall** [comment]
Thanks, fixed that one @jamesyoung28 !
